### ISSUE TITLE
After throwing spear I get this message:

### ISSUE THREAD

**Issue by ekt1701** [jcchurch/HuntTheYetiAlexa#2]
With the your update 548fd00, my previous issue with the spears is fixed.  However, I still get the message " If you would like to play again..." after I get the result from the spear throw.

if (session.attributes.game.isPlaying()) {
var aDirection = intent.slots.Direction.value;
session.attributes.game.launchSpear(aDirection);
response.askSSML(session.attributes.game.getConsequence()
- " If you would like to play again, say 'Begin Game' or say 'Stop'",
  "The game is over. Say 'Begin Game' or 'Stop'."
  );
  }

I was playing with 4 yetis in the cave, that was fun!  Also, does the spear travel more than one room?  A couple of times, even though nothing was near, I threw the spear in a random direction and it hit a yeti.

BTW, have you tried bst proxy https://bespoken.tools/blog/2016/08/24/introducing-bst-proxy-for-alexa-skill-development?  I use it when testing Hunt Yeti.

**Comment by jcchurch** [comment]
Thanks for play testing that for me. Looks like I still have some debugging to do.

To answer your question about the spear: Yes. When the hunter throws the spear, the spear travels until it hits either a yeti or it exits the bounds of the cave. The Yeti is removed from the game board. (Now that I think about it, the yeti smell still lingers in the air. Arg! More bug fixes.) You don't have to be right next to the Yeti to kill the yeti. You just have to have the right direction.

I still haven't tried bst proxy. I'm sure it's cool, but I'm not at the point were I need instant testing.

**Comment by ekt1701** [comment]
FYI, I saw this on the Alexa Slack: https://www.dropbox.com/s/xca7wcvtpabcb87/huntyeti.png?raw=1, I'm not sure where the poster got it from.

**Comment by jcchurch** [comment]
Ha! I made that last night!

**Comment by jcchurch** [comment]
So I've been playing my game with a 7 by 7 grid, 4 yeti, and 5 spear. It seems to work fine. Are you still having the issue? If not, I'm going to mark the bug as closed.

**Comment by ekt1701** [comment]
You can mark this issue closed. Yay!  That's pretty cool you had 175 people playing the game.
