### ISSUE TITLE
How to convert your audio files. 

### ISSUE THREAD

**Issue by tron1991** [jcchurch/HuntTheYetiAlexa#3]
Hey jcchurch, I was wondering how you managed to convert your audio files into correct music mp3 files. When I test my alexa skill, I can't seem to play my audio clip file(1min in duration). I followed the instructions on here, but I couldn't get it working https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/speech-synthesis-markup-language-ssml-reference#audio

  How did you convert the audio tracks.

**Comment by jcchurch** [comment]
Hi. I used the tool [avconv](https://libav.org/avconv.html) for converting my audio files.

Here's the command that I used to convert all of the files in a single directory (assuming that all files are audio).

    for i in *; do avconv -i $i -codec:a libmp3lame -b 48k -ar 16000 $i; done

Here's a similar example for a single file.

    avconv -i victory.mp3 -codec:a libmp3lame -b 48k -ar 16000 victory.2.mp3

Hope this helps.
